DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(16) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(128) NOT NULL UNIQUE,
    login varchar(128) NOT NULL UNIQUE,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(128) NOT NULL,
    description varchar(1024),
    release_date date,
    duration integer NOT NULL,
    mpa_id integer REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id integer NOT NULL REFERENCES users(id),
    friend_id integer NOT NULL REFERENCES users(id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes (
    user_id integer NOT NULL REFERENCES users(id),
    film_id integer NOT NULL REFERENCES films(id),
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id integer NOT NULL REFERENCES films(id),
    genre_id integer NOT NULL REFERENCES genres(id),
    PRIMARY KEY (film_id, genre_id)
);